feat #5 : 회원가입 기능
f-lab-edu/Wants-Market pull request #6
Opened 2022-11-13 06:31 UTC by sproutboot

- 유저 엔티티 설계
- spring validation 적용(필수 입력값 지정, 비밀번호 정규 표현식)
- 유저 아이디 중복체크 처리
- 유저 비밀번호 Bcrypt 암호화를 통해 저장
- 회원가입 기능 구현
- 회원가입 기능 테스트

2022-11-13 08:21 UTC, f-lab-joseph requested changes

2022-11-13 08:21 UTC, f-lab-joseph commented on src/test/java/com/wants/market/user/service/UserServiceImplTest.java
> +            System.out.println("오류 발생");
signup 이 성공하더라도 테스트는 성공으로 표기될 것 같습니다.

2022-11-23 05:27 UTC, gracefulife approved these changes

2022-11-23 05:29 UTC, f-lab-joseph approved these changes

2022-11-23 05:37 UTC, merged